stages:
  - build
  - package

default:
  tags:
    - shell
    - linux

build:
  stage: build
  needs: []
  script:
    - mkdir build && cd build
    - cmake ..
    - make

package:
  stage: package
  needs:
    - build
  script:
    - make install DESTDIR=$CI_PROJECT_DIR/install
    - cp -r install/* .
  artifacts:
    paths:
      - u8cc
      - lib/*
