stages:
  - build
  - package

default:
  tags:
    - shell
    - linux

build:
  stage: build
  needs: []
  script:
    - ./gradlew assemble

package:
  stage: package
  needs:
    - build
  script:
    - ./gradlew installReleaseLinux
    - cp build/install/main/release/linux/* .
  artifacts:
    paths:
      - u8cc
      - lib
