default:
  tags:
    - shell
    - linux

build:
  needs: []
  script:
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    expire_in: 10 mins
    paths:
      - build/*

test:
  needs:
    - build
  script:
    - cd build
    - ctest --output-on-failure
  allow_failure: true

package:
  needs:
    - build
  script:
    - make install DESTDIR=$CI_PROJECT_DIR/install
    - cp -r install/* .
  artifacts:
    paths:
      - u8cc
      - lib/*
