stages:
  - build
  - test
  - package

default:
  tags:
    - shell
    - linux

build:
  stage: build
  needs: []
  script:
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    expire_in: 10 mins
    paths:
      - build/*

test:
  stage: test
  needs:
    - build
  script:
    - cd build
    - ctest --progress --verbose
  allow_failure: true

package:
  stage: package
  needs:
    - build
  script:
    - cd build
    - make install DESTDIR="$CI_PROJECT_DIR"/install
    - cp -r "$CI_PROJECT_DIR"/install/usr/local/install/* "$CI_PROJECT_DIR"/
  artifacts:
    paths:
      - u8cc
