name: 'Test Report'

on:
  workflow_run:
    workflows: ['CMake']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    needs: CMake
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: GTest Tests
        path: '**/*.xml'
        reporter: java-junit
